### ISSUE TITLE
Trailing "/" in baseDir will it fail to find the right branch

### ISSUE THREAD

**Issue by johnlinp** [johnlinp/squirrel-bookmarks#7]
## Reproduction steps

1. Config `~/.squirrel.yaml`:

```yaml
# the base directory of the source code
baseDir: "~/dev/"

# the default branch when jumping to a bookmark
# should be a sub-directory name in baseDir
defaultBranch: "main"

# the bookmarks of relative paths in branch sub-directories
bookmarks:
  foo: bar
```

2. Type command `sq fix-abc`, which will jump to `~/dev/fix-abc/`
3. Type command `sq foo`

## Expected results

It should jump to `~/dev/fix-abc/bar/`

## Actual results

It jumped to `~/dev/main/bar/`
